// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXxH1wg5uttpRH-KfIVuf3Tqnw3YNpLwA',
    appId: '1:954310694615:web:bcd6a23ee03f0e93c08292',
    messagingSenderId: '954310694615',
    projectId: 'quickhire-96039',
    authDomain: 'quickhire-96039.firebaseapp.com',
    storageBucket: 'quickhire-96039.firebasestorage.app',
    measurementId: 'G-S7RMHQVBEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQSvqWtceD-a2xM-teTsGYgGQf5_JLEyU',
    appId: '1:954310694615:android:791e4a5a6cd04f6cc08292',
    messagingSenderId: '954310694615',
    projectId: 'quickhire-96039',
    storageBucket: 'quickhire-96039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq253sZw4bpeWXKVqxMMXWY7JfL2IcImI',
    appId: '1:954310694615:ios:ddf1e54b56f29c5dc08292',
    messagingSenderId: '954310694615',
    projectId: 'quickhire-96039',
    storageBucket: 'quickhire-96039.firebasestorage.app',
    iosBundleId: 'com.example.quickHire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq253sZw4bpeWXKVqxMMXWY7JfL2IcImI',
    appId: '1:954310694615:ios:ddf1e54b56f29c5dc08292',
    messagingSenderId: '954310694615',
    projectId: 'quickhire-96039',
    storageBucket: 'quickhire-96039.firebasestorage.app',
    iosBundleId: 'com.example.quickHire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXxH1wg5uttpRH-KfIVuf3Tqnw3YNpLwA',
    appId: '1:954310694615:web:84be5a461e670c03c08292',
    messagingSenderId: '954310694615',
    projectId: 'quickhire-96039',
    authDomain: 'quickhire-96039.firebaseapp.com',
    storageBucket: 'quickhire-96039.firebasestorage.app',
    measurementId: 'G-C43HYX9SM1',
  );
}
